# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.initrd.availableKernelModules = [ "xhci_pci" "nvme" "usb_storage" "sd_mod" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-intel" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" =
    { device = "/dev/mapper/luks-de1bfed3-5fb3-47c9-80dd-dccb90cee8c9";
      fsType = "ext4";
    };

  boot.initrd.luks.devices."luks-de1bfed3-5fb3-47c9-80dd-dccb90cee8c9".device = "/dev/disk/by-uuid/de1bfed3-5fb3-47c9-80dd-dccb90cee8c9";

  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/B86C-A036";
      fsType = "vfat";
      options = [ "fmask=0077" "dmask=0077" ];
    };

  swapDevices =
    [ { device = "/dev/mapper/luks-41c487f2-f414-43f2-be0b-b0590f069bdf"; }
    ];

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.intel.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
