# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.initrd.availableKernelModules = [ "xhci_pci" "ahci" "nvme" "usbhid" "usb_storage" "sd_mod" "sdhci_pci" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-intel" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" =
    { device = "/dev/mapper/luks-fbd83ce4-aec2-47aa-9e1d-5f419f02ce62";
      fsType = "ext4";
    };

  boot.initrd.luks.devices."luks-fbd83ce4-aec2-47aa-9e1d-5f419f02ce62".device = "/dev/disk/by-uuid/fbd83ce4-aec2-47aa-9e1d-5f419f02ce62";

  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/80CA-6D61";
      fsType = "vfat";
      options = [ "fmask=0077" "dmask=0077" ];
    };

  swapDevices =
    [ { device = "/dev/mapper/luks-3c7432fe-2f6c-484c-95ee-67da8afaf55b"; }
    ];

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.intel.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
